batch_size: 768
binarize_blocks: true
checkpoint_dir: models/test
cuda: 0
do_filter: true
do_one_hot: true
dropout: 0.33
embed_dropout: 0.33
embedder: glove
embedding_dim: 100
embedding_file: /home/estengel/glove/glove.6B.100d.txt
ff_dim: 1024
generate_after_n: 201
hidden_dim: 256
learn_rate: 0.0
max_seq_length: 60
n_classes: 2
n_heads: 8
n_shared_layers: 2
n_split_layers: 6
num_blocks: 1
num_epochs: 200
output_type: per-patch
patch_size: 8
resolution: 64
top_only: true
train_path: blocks_data/trainset_v2.json
traj_type: flat
val_path: blocks_data/small_devset.json
warmup: 4000
zero_weight: 0.01
